# 配置tomcat端口
server:
  port: 80

#配置上传文件 大小限制
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  freemarker:
    cache:  false # 缓存配置
    suffix: .html #模版后缀名，默认为ftl
    charset: UTF-8 # 文件编码
    template-loader-path: classpath:/templates/
  thymeleaf:
    cache: false
    check-template: true # 建议模版是否存在
    enabled: true # 是否启用
    encoding: UTF-8 # 编码
    excluded-view-names:  # 从解析中排出的视图名称列表（用逗号来分割）
    mode: HTML5 # 模版模式
    prefix: classpath:/templates/ # 模版存放路径
    suffix: .html #模版后缀

  ##jsp
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    #favicon:
      #enabled: false # 是否使用springboot 原生的网站图标（就是那个叶子的图标）
  devtools: # 热启动
    restart:
      enabled: true
      additional-paths: src/main/java
  mail:
    host: smtp.qq.com # 发送邮件服务器
    port: 587 # 发送端口号
    username: 2725134584@qq.com # 发送账号
    password: sbvyiyyoakihdgjb # 授权码
#    username: 1215765064@qq.com # 发送账号
#    password: mykhueqfuiyjhdjf # 授权码
    protocol: smtp
    properties:
      mail:
        smtp:
         auth: true # 开启身份验证 这个不能缺失，缺失的话，项目启动不了
  data:
    rest:
      base-path: /api # 定制根路径
debug: false # 日志是debug 模式
